Base const:
  G:  6.674e-11 # гравитационная постоянная
  stellar_constant:  1365 # звёздная постоянная [Вт/м]
  C:  4180 # удельная теплоёмкость воды
  R:  6371000
  alfa:  0.3977 #ось наклона земли
  Growth_constant: 1.5
  M: 5.9742e+24
  Md: 2.5e+13
Variable parameters:
  k:  (5.08 * 10**11)/(3.14 * R**2 * alfa)
  g:  (G*M)/(R**2)
  h:  Growth_constant/g
  #средняя температура планеты
  T:  k * stellar_constant
  #Энергия от солнечных панелей 
  E_silar_panel:  0.24 * stellar_constant
  #Энергия от ядерных реакторов
  E_nuclear_reactor:  (0.6 * 5555)/(C * 633)
Functions:
  food:
    arguments:
      - p
      - P
      - F
    formula: F + (((p))**(1+p/P)*(T * (h**2))-P/10) if F + (((1+p))*(0.25*T * 10*(h**2)) - (P/10)) > 0 else 0.0001
  energy:
    arguments:
      -t
      -p
      -energy
    formula:
      (energy + 0.01 * ((((E_silar_panel + E_nuclear_reactor) ) * (p)**(2+p/P)) - 200*P)) if  p/P>0.3 else (energy + 0.01 * ((((E_silar_panel + E_nuclear_reactor) ) * (p)**(1+p/P)) - 200*P))

  
  population:
    arguments:

      -F
      -energy
      -P
    formula:
      (P + ((((4*F * energy))**(8/(energy*F)))-(P/20)))
#      (energy*food)*P*(1 - P)
  resources:
    arguments:
      -res
      -p
      -P
      -E
    formula:
     res + 0.001 *((0.01*(p**(p/P) * E) - 4*P)) if p/P>0.2 else res + 0.001 *((0.001*(p**(p/P) * E) - 20*P**(1+p/P)))
  Ax:
    arguments:
      -x
      -y
      -x0
      -y0


    formula: (G * Md * (x0 - x)) / (((x - x0)**2 + (y - y0)**2))**1.5

  Ay:
    arguments:
      -x
      -y
      -x0
      -y0


    formula: (G * Md * (y0 - y)) / (((x - x0)**2 + (y - y0)**2))**1.5







